### PR TITLE
Execute jasmine instead of previous bash script.

### PR DESCRIPTION
**Pull request by kimegede**
@emolr can you please help confirm this?

### CODE REVIEW

**Comment by ankr** [comment]
Thanks a lot buddy!

**Comment by emolr** [comment]
It looks good! Actually @kimegede, now a days you don't need to specify the full path to the bin file :) 

`"test": "jasmine` should be sufficient. 

They have changed it so it looks in it's own project first, and then traversing upwards from there until it finds it :)

**Comment by kimegede** [comment]
Thanks, that's handy - I like it!
And nice to know :)

**Comment by dennishn** [comment]
Some times you just gotta
Peter don't care

```
![Alt Text](https://github.com/{user}/{repo}/raw/master/path/to/image.gif)
```

**Pull request merged**
